### ISSUE TITLE
初期化不良

### ISSUE THREAD

**Issue by IwasakiYuuki** [Spacekoki/Grade4#2]
これだとc3しか初期化されてないから，すごいことになるよ
さすがにこれを提出したわけではないと思うけど
https://github.com/Spacekoki/Grade4/blob/0c557394c30ae69b14a63b2109bc1e429a044cdb/ke2/ke2-13.c#L8

**Comment by IwasakiYuuki** [comment]
`srand((unsigned)time(NULL));`
この行追加しないと乱数にならないぞ。
実行ごとに毎回同じ値になってる。

**Comment by Spacekoki** [comment]
ほげー

**Comment by Spacekoki** [comment]
こんぱいらによるのかな
わいmingwのgccだけど
`0.0714 0.0533 0.8619`
こうなるよ

**Comment by IwasakiYuuki** [comment]
環境依存はアウトやろ
